name: "⚙️ Feature request"
description: Submit a feature request
labels: ["triage-needed", "feature-request"]

body:
- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe
    description: A clear and concise description of what the problem is.

- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen.
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
    
- type: checkboxes
  id: version-check
  attributes:
    label: Have you set this feature request's Milestone field to Future Release?
    options:
      - label: I have set this issue's milestone to Future Release
        required: true
        
